name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: |
          npm add --include=dev purescript@0.15 spago
          npm run build

      - name: Tests
        run: |
          npx spago test
